# This workflow runs test

name: tests

on:
  pull_request:
    branches:
      - "main"
      - "master"
      - "develop"
  push:
    branches:
      - "main"
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.x
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lyncs_setuptools

      - name: Install via pip
        run: |
          sudo pip install -e .[all]

      - name: Run tests
        run: |
          coverage run --rcfile=setup.cfg -m pytest

      - name: Coverage report
        run: |
          coverage report

      - name: Upload Coverage report
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && matrix.py-version == '3.x' }}
        run: |
          coverage xml
          export CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
          bash <(curl -s https://codecov.io/bash) -f ./coverage.xml -n $(lyncs_setuptools name)
